### ISSUE TITLE
skaffold run and dev accept remote skaffold.yaml

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#131]

**Comment by dgageot** [comment]
@r2d4 Can you provide more details on what you'd want to see?

**Comment by r2d4** [comment]
The behavior from `kubectl -f`

It supports

Remote manifest 
`kubectl -f https://example.com/resource.yaml`

skaffold.yaml piped to stdin
`kubectl -f -`

and the normal
`kubectl -f resource.yaml`

**Comment by dgageot** [comment]
dibs

**Comment by r2d4** [comment]
Its yours!  I started investigating if we could reuse some of the code from kubectl, but the code isn't actually that great so its probably a lot easier to just write it up yourself

https://github.com/kubernetes/kubernetes/blob/bb500a73b618b40e8e5ef0955861183ebd325259/pkg/kubectl/resource/builder.go#L139-L172
