### ISSUE TITLE
Make mailing list archives public

### ISSUE THREAD

**Issue by jbeda** [GoogleCloudPlatform/skaffold#144]
I shouldn't have to join your mailing list to see the archives.

<img width="478" alt="screen shot 2018-03-07 at 9 26 17 am" src="https://user-images.githubusercontent.com/37310/37107683-dc9b7522-21e9-11e8-8801-994716421bf0.png">

**Comment by pradeepto** [comment]
+1 on what @jbeda said. Would be nice to have a more open list.

**Comment by r2d4** [comment]
Absolutely, oversight on our part.  Should be open now! (there aren't any threads yet)
