### ISSUE TITLE
Logs of init containers

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#145]
We should make sure that we also stream logs from init containers.

This possibly already works, but I suspect there is some extra work to be done.

**Comment by dgageot** [comment]
I think it does but I need to check

**Comment by demisx** [comment]
Guys, the streaming logs from init containers have red container name prefixes (see attached) which make them appear as errors. Is this something that's controlled by skaffold or something else? I would love to change this so red is only reserved for error messages, yellow for warnings etc. My apologies if this question is not exactly on topic of this issue.

![Screen Shot 2019-04-30 at 6 22 00 PM](https://user-images.githubusercontent.com/4452412/57002548-1473f480-6b75-11e9-8098-a5975fba3571.gif)

**Comment by nkubala** [comment]
@demisx yes we're just picking colors from a pool, nothing smarter than that. it would be tough to do different colors for different log levels across multiple pods, but we're open to ideas for improvements!

**Comment by demisx** [comment]
Maybe as a  work around just get rid of the red color? It's usually used for errors and every time I see a bunch of red in the skaffold log my heart drops. :)
