### ISSUE TITLE
examples: docker build fails

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/skaffold#149]
```
examples/getting-started master $ skaffold run
Starting build...
Sending build context to Docker daemon  1.024kB
ERRO[0000] run: running skaffold steps: run: build step: running build: docker build: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
examples/getting-started master $ ls
Dockerfile  k8s-pod.yaml  main.go  skaffold.yaml
```

running from HEAD (a40cc72d9891e6b6cf617837b2ab8efcc08673fd) for both cmd/skaffold and the examples.

```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by viglesiasce** [comment]
Hey @broady!

Can you try running that from the root of the repo?

I think there is another issue open to make all the examples work from the local dir of the example.

**Comment by viglesiasce** [comment]
Should be:
`skaffold run -f examples/getting-started/skaffold.yaml`

**Comment by dgageot** [comment]
Should the `workspace` and `paths` be relative to the parent folder of `skaffold.yaml`?

**Comment by viglesiasce** [comment]
yeah i think we should make that change happen, including the update to the getting started doc.

**Comment by r2d4** [comment]
Agreed, not sure why I made it relative to the binary - probably an oversight

**Comment by r2d4** [comment]
Interesting question though, whats the path of `skaffold.yaml` once we merge #131?
