### ISSUE TITLE
allow a tag to be provided on the command line of `skaffold run`

### ISSUE THREAD

**Issue by jstrachan** [GoogleCloudPlatform/skaffold#152]
When folks want to make public releases of images/charts/yaml they may want more control over the image tags that are used for the docker images. 

So it might be nice to allow folks to pass that in on the CLI if they want. e.g. 

```
skaffold run --tag 1.2.3
```
From a quick noodle of the code it looks a fairly easy patch, adding an optional tag to the CLI `SkaffoldOptions`. Lemme submit a PR...

**Comment by r2d4** [comment]
Commented on the PR, but this is definitely a feature we want to have.
