### ISSUE TITLE
Allow git commit short option

### ISSUE THREAD

**Issue by Joeskyyy** [GoogleCloudPlatform/skaffold#157]
Would be nice to not have the image tag be something so long (optionally) especially for those of us with long docker registry URLs.

I was able to get a small mock up of this working by changing https://github.com/GoogleCloudPlatform/skaffold/blob/master/pkg/skaffold/build/tag/git_commit.go#L55 to use `git rev-parse --short HEAD` instead. I'm not comfortable enough in Go at this time to know the best approach to make this an option, so if someone much smarter than me could implement it, I'd love you forever!

I'm thinking either it could be added as a sub option under the gitCommit type, or entirely separate type itself of some sort.

**Comment by r2d4** [comment]
Thanks for opening up the issue, the options you laid out are all great!

I actually think its fine to just change the command itself to add the --short flag.  In the future, if we need tagger to be more functional, we can make it a full type and pass more options.

Let me know if you feel comfortable sending that PR, if not, I'm sure someone can pick it up.
