### ISSUE TITLE
Dockerfile ADD directive is not correctly handled 

### ISSUE THREAD

**Issue by AMecea** [GoogleCloudPlatform/skaffold#158]
Hello, I think I found a bug in skaffold dockerfiles watcher.  In my Dockerfile I have ADD directive that tries to copy from a remote url a file:
```
# My Dockerfile
ADD https://repo.percona.com/apt/percona-release_0.1-5.stretch_all.deb /tmp/
```
In the [ADD](https://docs.docker.com/engine/reference/builder/#add) doc is specified that: `The ADD instruction copies new files, directories or remote file URLs from <src> and adds them to the filesystem of the image at the path <dest>.`

This is the error that I get:
```
run: running skaffold steps: running watch: adding deps for artifact: getting dockerfile dependencies: expanding dockerfile paths: getting file info: stat https:/repo.percona.com/apt/percona-release_0.1-5.stretch_all.deb: no such file or director
```

Thank you

**Comment by r2d4** [comment]
Thanks for the issue, we don't handle this yet! I'll fix it
