### ISSUE TITLE
changelog uses the wrong URL for downloads

### ISSUE THREAD

**Issue by jstrachan** [GoogleCloudPlatform/skaffold#179]
might be a copy/paste gremlin maybe ;) I tried copy/pasting the instructions from the shiny new [0.2.0 release](https://github.com/GoogleCloudPlatform/skaffold/releases/tag/v0.2.0) into a `Dockerfile` and got a build failure.

I think it needs to change from
```
### Linux
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.2.0/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin

### macOS
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.2.0/skaffold-darwin-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
```
to:

```
### Linux
curl -Lo skaffold https://github.com/GoogleCloudPlatform/skaffold/releases/download/v0.2.0/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin

### macOS
curl -Lo skaffold https://github.com/GoogleCloudPlatform/skaffold/releases/download/v0.2.0/skaffold-darwin-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
```

**Comment by dgageot** [comment]
@jstrachan It looks like it's fixed now.

**Comment by r2d4** [comment]
I verified that those downloads work now. Please reopen if you still can't access them.  We upload both to our release bucket at `https://storage.googleapis.com/skaffold/releases/` and the github releases page.

There are bound to be many copy/paste gremlins before I finish setting up all the automation so thatnks for catching this :)
