### ISSUE TITLE
Using minikube context for local development

### ISSUE THREAD

**Issue by nicolls1** [GoogleCloudPlatform/skaffold#196]
I updated to 0.2.0 and now when I run skaffold dev it is finding the 'Docker for Desktop context' as well as the minikube context and printing:

```
Found minikube or Docker for Desktop context, using local docker daemon.
```

How do I change this to default to the minikube context?

I tried doing `kubectl config set-context minikube` as it seems the context is being used here: https://github.com/GoogleCloudPlatform/skaffold/blob/master/pkg/skaffold/runner/runner.go#L53, but that did not work. Thanks!

**Comment by dlorenc** [comment]
kubectl set-context is a bit confusing, it doesn't actually set the context. I think you need kubectl use-context.

**Comment by nicolls1** [comment]
Hi,
Thanks for your response. I tried:
```
kubectl config use-context minikube
```
and `Found minikube or Docker for Desktop context, using local docker daemon.` is still being printed.

**Comment by dlorenc** [comment]
I think I might be misunderstanding something.

```
Found minikube or Docker for Desktop context, using local docker daemon
```

I think that's the correct output. What's the desired behavior?
