### ISSUE TITLE
skaffold is slow to start

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/skaffold#218]
Each time skaffold is started, it retrieves the config for every base image used by the artifacts.
Most of the time, those images are local. If there's a way to use the local data, we should do so.

**Comment by dlorenc** [comment]
We should definitely do this when using a local builder. It's not only a performance thing, it's also about correctness. You could have a local image that has the same name but a different configuration from a remote one.

**Comment by dlorenc** [comment]
Though if we're using a cloud builder we need to check the registry.

**Comment by dgageot** [comment]
This is fixed by https://github.com/GoogleCloudPlatform/skaffold/pull/224
