### ISSUE TITLE
What should be deployed if only one artifact is updated?

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/skaffold#221]
When I run `skaffold dev` on a project with 4 artifacts, I expect than the deploy doesn't fail when only one artifact is rebuilt.

I currently fails which such an error:
```
Build complete.
Starting deploy...
WARN[0251] run: deploy step: deploying manifests: joining template keys to image tag: No build present for dgageot/petstore-front
```

**Comment by r2d4** [comment]
Yeah this is a bug.  I proposed keeping a map of artifact to latest build result, and then deploy gets the full list of latest build results everytime, even if some of those weren't rebuilt. That leans on the fact that the tools we implement should be declarative and no-op if nothing has changed.
