### ISSUE TITLE
Skaffold ran out of colors

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#263]
```
panic: runtime error: index out of range

goroutine 281 [running]:
github.com/GoogleCloudPlatform/skaffold/pkg/skaffold/kubernetes.(*LogAggregator).nextColor(0xc42093e9b0, 0x2098078)
```
What if we picked the color from 

checksum % num_colors? That way we ensure that we always get the same colors for the same artifacts

**Comment by dgageot** [comment]
This is fixed in https://github.com/GoogleCloudPlatform/skaffold/pull/260
