### ISSUE TITLE
skaffold dev fails to copy file

### ISSUE THREAD

**Issue by julianvmodesto** [GoogleCloudPlatform/skaffold#265]
After running `skaffold dev`, the first run succeeds.

When I copy my binary into the workspace that skaffold is watching, then a new build is triggered as expected, but the `docker build` errors with:

```
Starting build...
ERRO[0127] Can't add file path/to/my/workspace/binary to tar: archive/tar: write too long
Sending build context to Docker daemon  6.581MB
Step 1/5 : FROM alpine
 ---> 3fd9065eaf02

# ...
# continues to deploy the broken image such that Pod fails
```

This is unexpected. My binary is 61M for reference.

**Comment by dgageot** [comment]
Hi @clanstyles, thanks for the report!
 + Can you tell us which version of skaffold you are using?
 + Does `skaffold docker deps` works?
 + Does `skaffold docker context` works?

**Comment by julianvmodesto** [comment]
Oops wrong @ tag :)

Version below + both commands work:
```
$ skaffold version
v0.2.0

$ skaffold docker deps -v info
INFO[0000] Skaffold &{Version:v0.2.0 GitVersion: GitCommit:eb0fd0223bb9ec640f1031bb8c9858ef22338e01 GitTreeState:clean BuildDate:2018-03-09T22:47:32Z GoVersion:go1.10 Compiler:gc Platform:darwin/amd64}
INFO[0002] Found dependencies for dockerfile [my-files]
# ... paths to files ...

$ skaffold docker context -v info
INFO[0000] Skaffold &{Version:v0.2.0 GitVersion: GitCommit:eb0fd0223bb9ec640f1031bb8c9858ef22338e01 GitTreeState:clean BuildDate:2018-03-09T22:47:32Z GoVersion:go1.10 Compiler:gc Platform:darwin/amd64}
INFO[0000] Dockerfile
INFO[0000] /path/to/Dockerfile
INFO[0002] Found dependencies for dockerfile [my-files]
```

My replacement workflow has been `cp my/binary to/skaffold/artifact/directory/ && skaffold run -f skaffold.yaml` which works for now.

**Comment by dgageot** [comment]
@julianvmodesto Can you please try again with version 0.3.0? That would be awesome

**Comment by julianvmodesto** [comment]
My use case is fixed, thanks!

Note that one potential bug I noticed is new files aren't watched by `skaffold dev`.

e.g. `touch foobar` into one of the watched directories doesn't do anything.
