### ISSUE TITLE
Handle docker auth to DockerHub

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#271]
We currently don't inject dockerhub credentials for images without a `docker.io` prefix. This is something that gets resolved in the docker CLI, so I think its something we need to handle here. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/skaffold-users/fmnS3y3zOno/6gG6rdnaCAAJ

**Comment by ryuheechul** [comment]
I tried with `docker.io` prefix and even with that, it still couldn't push the image.

```
WARN[0004] run: build step: running push: denied: requested access to the resource is denied 
```
