### ISSUE TITLE
GitTagger now needs to be ran from root git dir

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#274]
We broken some subtle functionality in #215. The git command can detect the repository even if ran from a subdirectory. The go-git library doesn't support this yet. This means for our getting-started example, `skaffold run` is broken since it defaults to the git tagger.

https://github.com/src-d/go-git/issues/765

```
[~/go/src/github.com/GoogleCloudPlatform/skaffold/examples/getting-started]skaffold run
ERRO[0001] run: running skaffold steps: run: build step: build step: generating tag: opening git repo: repository does not exist
```

**Comment by dgageot** [comment]
@r2d4 Let me TAL since I broke it
