### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by bhack** [GoogleCloudPlatform/skaffold#277]
As also [Draft](https://github.com/Azure/draft) is still in its Microsoft/Azure repository is there instead a plan for this project to move in a more independent repository like Kuberenetes?

**Comment by r2d4** [comment]
Not plans yet - our first step is to get together a working group together consisting of a few different projects tackling the developer workflow space. The next steps for the broader community will probably be decided there. 

We'll post an announcement on https://groups.google.com/forum/#!forum/skaffold-users once we get this set up!

**Comment by bhack** [comment]
Thanks

**Comment by r2d4** [comment]
cc @kimsterv

**Comment by kimsterv** [comment]
A working group is being actively discussed here:

https://groups.google.com/forum/#!topic/kubernetes-dev/YcjXRDrCdbI

I'll follow-up again once it's formed.

**Comment by bhack** [comment]
@kimsterv For the wg: https://blog.hasura.io/draft-vs-gitkube-vs-helm-vs-ksonnet-vs-metaparticle-vs-skaffold-f5aa9561f948

**Comment by bhack** [comment]
https://youtu.be/McwwWhCXMxc
