### ISSUE TITLE
Microsoft unable to update

### ISSUE THREAD

**Issue by RoguesHollow** [GoogleCloudPlatform/skaffold#278]
Issues without logs and details are more complicated to fix.
Please help us!

### Expected behavior
Unable to update Microsoft 10 March 19, 2018 update

### Actual behavior
receiving the following error messages:

Failed to install: KB4011675
Excel 2010 32-Bit Edition failed to install

Failed to install: 0X80070bc2

Failed to install: 0X80024200d 
64 based system

### Information

```
Skaffold version: version...
Operating system: 10
Content of skaffold.yaml: ...
```
### Steps to reproduce the behavior

  1. When I restart the computer to update I get the above messages???
  2. Then it instructs me to restart again to update. Have done this repeatedly with the same message.

**Comment by r2d4** [comment]
Have you tried turning it off and back on again?

**Comment by r2d4** [comment]
This an issue tracker for an open source project called skaffold. We won’t be able to help you with Windows issues, Sorry!
