### ISSUE TITLE
Example with multiple images and deployments

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/skaffold#282]
How would I use Skaffold to spin up multiple backend services at once? Is there an example of this?

**Comment by clanstyles** [comment]
Hey, I know you guys are really busy, does anyone have a small example and I can build on it from there.

**Comment by r2d4** [comment]
@clanstyles Sorry about that! I added one a few days ago but forgot to comment on this issue 

https://github.com/GoogleCloudPlatform/skaffold/tree/master/examples/microservices

**Comment by clanstyles** [comment]
Thanks for the update! Also thanks for updating the title!

**Comment by dgageot** [comment]
I'm going to close this issue. @clanstyles feel free to reopen if there's more to be added.
