### ISSUE TITLE
Support profiles

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/skaffold#299]
I think it would be useful for the `skaffold.yaml` to support profiles that can be activated with a command line flag. Those profiles would basically override the default configuration (aka default profile)
Something along this lines:
```
$ cat skaffold.yaml
apiVersion: skaffold/v1alpha1
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: k8s-skaffold

$ skaffold build -p gcb
```

**Comment by dgageot** [comment]
Something along those lines: http://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by Eronarn** [comment]
We're looking at using skaffold and would love to see this so we could easily switch between development minikube for speed and a staging cluster for sharing with others.
