### ISSUE TITLE
Bad exit code on config parsing error

### ISSUE THREAD

**Issue by Trane9991** [GoogleCloudPlatform/skaffold#302]
Hey, I'm using skaffold on the CI. Skaffold version got updated, config file format changed so deployment failed but reported as the success.
```
$ skaffold run -f skaffold.yaml ; echo ExitCode: $?
ERRO[0000] run: parsing skaffold config: yaml: unmarshal errors:
  line 12: cannot unmarshal !!map into string
ExitCode: 0
```
### Expected behavior
ExitCode should be non-0

### Actual behavior
ExitCode is 0
### Information

```
Skaffold version: v0.3.0
Operating system: Mac/Linux
```

**Comment by viglesiasce** [comment]
Hey @Trane9991!

Check out the note in the CHANGELOG around breaking config changes:
https://github.com/GoogleCloudPlatform/skaffold/blob/v0.3.0/CHANGELOG.md#v030-release---3292018

In the near term future there will be a command that fixes these things automatically, currently that functionality is in #291.

**Comment by r2d4** [comment]
Thanks for using this already! We should absolutely return a real exit code on breaks
