### ISSUE TITLE
Conditionally rebuild artifacts from watch

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/skaffold#36]
Currently, all artifacts are rebuilt after one source file changes, and changes during the build and deploy pipeline are ignored.

**Comment by dgageot** [comment]
Instead of triggering a build on the first change event, we could wait for say 500ms and trigger a build only if no event has been received since.

Then we need to decide if a build should be interrupted in a change event occurs after it's started.

**Comment by dgageot** [comment]
@r2d4 This should be fixed now, right?
